[buildPlans.mofis-0_3]
family = "Mofis 0.3"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = false
export-glyph-names = true

[buildPlans.mofis-0_3.variants]
inherits = "ss03"

[buildPlans.mofis-0_3.variants.design]
capital-j = "descending-serifed"
#capital-j = "descending-serifless"
capital-q = "crossing"
# f = "flat-hook-extended"
f = "flat-hook-extended-crossbar-at-x-height"
l = "serifed-flat-tailed"
# r = "compact-serifless"
t = "flat-hook"
long-s = "flat-hook-descending-middle-serifed-xh"
eszet = "sulzbacher-descending-middle-serifed-xh"
# asterisk = "hex-mid"
asterisk = "penta-mid"

zero = "oval-tall-slashed"
two = "straight-neck"
three = "flat-top"
four = "closed"
five = "oblique-upper-left-bar"
six = "open-contour"
# seven = "straight-serifed"
eight = "two-circles"
nine = "open-contour"
percent = "rings-continuous-slash"
question = "smooth"


digit-form = 'old-style'
